# Generated by Django 6.0.3 on 2026-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cyberbullying', 'Cyberbullying'), ('Online Harassment', 'Online Harassment'), ('Threats', 'Threats'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
